version: "3.8"
services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW
    networks:
      - mysql-net
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3309:3306"
    command: --server-id=2 --relay-log=mysql-relay-bin --read-only=1
    depends_on:
      - mysql-master
    networks:
      - mysql-net
volumes:
  master-data:
  slave-data:
networks:
  mysql-net:
